apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "djl-serving.fullname" . }}
  labels:
    {{- include "djl-serving.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "djl-serving.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "djl-serving.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: djl-serving
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          command: ["/usr/bin/djl-serving"]
          args: ["-m", "{{ .Values.model.url }}"]
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /ping
              port: http
          readinessProbe:
            httpGet:
              path: /ping
              port: http
