[metadata]
format.version = "1.1"

[versions]
djl = "0.33.0"
commonsCli = "1.9.0"
commonsCodec = "1.18.0"
commonsCsv = "1.14.1"
commonsIo = "2.19.0"
netty = "4.1.121.Final"
slf4j = "2.0.17"
jsonpath = "2.9.0"

testng = "7.11.0"

[libraries]
huggingface-tokenizers = { module = "ai.djl.huggingface:tokenizers" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }
commons-io = { module = "commons-io:commons-io", version.ref = "commonsIo" }
commons-cli = { module = "commons-cli:commons-cli", version.ref = "commonsCli" }
commons-codec = { module = "commons-codec:commons-codec", version.ref = "commonsCodec" }
apache-commons-csv = { module = "org.apache.commons:commons-csv", version.ref = "commonsCsv" }
netty-http = { module = "io.netty:netty-codec-http", version.ref = "netty" }

testng = { module = "org.testng:testng", version.ref = "testng" }
