[package]
name = "lmbench"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
base64 = "0.22.1"
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "4.5.53", features = ["derive"] }
env_logger = "0.11.8"
futures-util = "0.3.30"
hex = "0.4"
jsonpath_lib = "0.3.0"
lazy_static = "1.4.0"
log = "0.4"
parking_lot = "0.12"
rand = "0.9.2"
reqwest = { version = "0.12.26", features = ["json", "multipart", "stream"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_urlencoded = "0.7"
tokenizers = { version = "0.22.2", features = ["http"] }
tokio = { version="1.48.0" , features = ["rt-multi-thread", "macros", "fs"]}
indicatif = { version = "0.17.8", features = ["tokio"] }
once_cell = "1.19.0"

[lib]
name = "lmbench"
path = "src/lib.rs"

[[bin]]
name = "lmbench"
path = "src/main.rs"
